name: Build and deploy JAR app to Azure Web App - SIGEMAGESTION

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3CE63E84F23F425C9041148CB0077931 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F98C5624E1A94C10B5C81D6AF984A084 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C4CF806A9794F0190E85C821730D461 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SIGEMAGESTION'
          slot-name: 'Production'
          package: '*.jar'

      - name: Configure startup command
        uses: azure/cli@v1
        with:
          azcliversion: 2.45.0
          inlineScript: |
            az webapp config set --name SIGEMAGESTION --resource-group SIGEMA --startup-file "java -jar tu-app.jar"
